# Generated by Django 5.1.5 on 2025-01-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_adminuser_password_alter_adminuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
